# Generated by Django 5.2.3 on 2025-07-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='Dealer Email'),
        ),
    ]
